version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx-server
    restart: on-failure
    volumes:
    - ./deploy/shared/conf/nginx/magento.conf:/etc/nginx/conf.d/default.conf
    - ./src:/var/www/html
    ports:
    - 80:80
    depends_on:
      - php
      - db
    networks:
      - default
  db:
    image: mariadb
    container_name: mariadb
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
    networks:
      - default
  php:
    image: library/php:7.4-fpm-alpine
    container_name: php
    volumes:
    - ./src:/var/www/html
    - ./deploy/php/php.ini:/usr/local/etc/php/php.ini
    ports:
    - 9000:9000
    networks:
      - default





