version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx-server
    restart: on-failure
    volumes:
    - ./deploy/shared/conf/nginx/magento.conf:/etc/nginx/conf.d/default.conf
    - ./src:/var/www/html
    ports:
    - 80:80
    networks:
      - default
  db:
    image: mariadb
    container_name: mariadb
    restart: on-failure
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: magento
    networks:
      - default




